# Generated by Django 4.0.2 on 2022-02-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Yardımcı Link')),
                ('url', models.URLField(verbose_name='Link')),
                ('isActive', models.BooleanField(default=True, verbose_name='Aktif/Pasif')),
            ],
        ),
        migrations.CreateModel(
            name='TopBarContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=80, verbose_name='Metin')),
                ('image', models.ImageField(upload_to='topbar')),
            ],
        ),
    ]
