# Generated by Django 4.0.2 on 2022-02-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sublinks_topbarcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='topbarcontent',
            name='content',
            field=models.CharField(blank=True, choices=[('Görsel', 'Görsel'), ('Metin', 'Metin')], max_length=10),
        ),
    ]
