# Generated by Django 4.0.2 on 2022-03-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_topbarcontent_url_alter_topbarcontent_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, verbose_name='Başlık')),
                ('image', models.ImageField(upload_to='main_slider')),
                ('paragraph', models.CharField(max_length=90, verbose_name='Metin')),
                ('url', models.URLField(verbose_name='Link')),
                ('isActive', models.BooleanField(default=True, verbose_name='Aktif/Pasif')),
            ],
        ),
    ]
