# Generated by Django 4.0.2 on 2022-03-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_slideritem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideritem',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Başlık'),
        ),
    ]
