# Generated by Django 4.0.2 on 2022-03-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_slideritem_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, verbose_name='Başlık')),
                ('file', models.FileField(upload_to='category_banner')),
                ('url', models.URLField(verbose_name='Link')),
                ('isActive', models.BooleanField(default=True, verbose_name='Aktif/Pasif')),
            ],
        ),
    ]
