# Generated by Django 4.0.2 on 2022-03-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_categorybanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorybanner',
            name='file',
            field=models.ImageField(upload_to='category_banner'),
        ),
    ]
