# Generated by Django 4.0.2 on 2022-03-04 07:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Ürün Adı')),
                ('main_image', models.ImageField(upload_to='products/<django.db.models.fields.CharField>')),
                ('style_image', models.ImageField(upload_to='products/<django.db.models.fields.CharField>')),
                ('zoom_image', models.ImageField(upload_to='products/<django.db.models.fields.CharField>')),
                ('description', ckeditor.fields.RichTextField()),
                ('is_active', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('is_exclusive', models.BooleanField(default=False)),
                ('is_contract', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('categories', models.ManyToManyField(blank=True, to='catalog.Category')),
            ],
        ),
    ]
