# Generated by Django 4.0.2 on 2022-03-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_composition_physicaltest_rename_category_usage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usage',
            name='slug',
        ),
        migrations.AddField(
            model_name='composition',
            name='name',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='compositions',
            field=models.ManyToManyField(blank=True, to='catalog.Composition'),
        ),
    ]
