# Generated by Django 4.0.2 on 2022-03-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_usage_slug_composition_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.PositiveIntegerField(default=300),
        ),
    ]
