# Generated by Django 4.0.2 on 2022-03-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_easyclean',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_fr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_natural',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_recycled',
            field=models.BooleanField(default=False),
        ),
    ]
