# Generated by Django 4.0.2 on 2022-03-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_delete_physicaltest_product_color_fastness_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Height as Width', max_length=50)),
                ('description', models.CharField(default=None, max_length=100)),
                ('icon', models.ImageField(upload_to='settings')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='design_direction',
            field=models.ManyToManyField(blank=True, to='catalog.DesignDirection'),
        ),
    ]
