# Generated by Django 4.0.2 on 2022-03-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_designdirection_product_design_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(default=None, max_length=100)),
                ('icon', models.ImageField(upload_to='settings/care_instructions')),
            ],
        ),
        migrations.AlterField(
            model_name='designdirection',
            name='icon',
            field=models.ImageField(upload_to='settings/design_directions'),
        ),
    ]
