# Generated by Django 4.0.2 on 2022-03-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_careinstruction_alter_designdirection_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default='1111.1D', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='horizontal_repeat',
            field=models.DecimalField(blank=True, decimal_places=1, default=1, max_digits=2),
        ),
        migrations.AddField(
            model_name='product',
            name='vertical_repeat',
            field=models.DecimalField(blank=True, decimal_places=1, default=1, max_digits=2),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.PositiveIntegerField(default=220),
        ),
        migrations.AlterField(
            model_name='designdirection',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='designdirection',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.PositiveIntegerField(),
        ),
    ]
