# Generated by Django 4.0.2 on 2022-03-23 09:04

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(upload_to=catalog.models.Product.generate_main_filename),
        ),
        migrations.AlterField(
            model_name='product',
            name='style_image',
            field=models.ImageField(blank=True, null=True, upload_to=catalog.models.Product.generate_style_filename),
        ),
        migrations.AlterField(
            model_name='product',
            name='zoom_image',
            field=models.ImageField(blank=True, null=True, upload_to=catalog.models.Product.generate_zoom_filename),
        ),
        migrations.AlterField(
            model_name='productvariantimages',
            name='image',
            field=models.ImageField(upload_to=catalog.models.ProductVariantImages.generate_filename),
        ),
    ]
