# Generated by Django 4.0.2 on 2022-03-23 09:33

import catalog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_collection_collectionimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='is_contract',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collection',
            name='is_exclusive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collection',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collection',
            name='main_image',
            field=models.ImageField(default=None, upload_to=catalog.models.Collection.generate_main_filename),
        ),
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.collection'),
        ),
    ]
