# Generated by Django 4.0.2 on 2022-03-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_collection_slug_alter_product_compositions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color_fastness',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='light_fastness',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='martindale',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='pilling_abrasion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='seam_slippage',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='tear_strenght',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='tensile_strenght',
            field=models.CharField(max_length=50),
        ),
    ]
