# Generated by Django 4.0.3 on 2022-03-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_alter_product_code_alter_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('icon', models.ImageField(upload_to='feature_icons')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_easyclean',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_fr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_natural',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_recycled',
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.ManyToManyField(blank=True, to='catalog.feature'),
        ),
    ]
