# Generated by Django 4.0.3 on 2022-03-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_feature_remove_product_is_easyclean_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='icon',
            field=models.FileField(upload_to='feature_icons'),
        ),
    ]
