# Generated by Django 4.0.3 on 2022-04-01 12:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_product_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 1, 12, 19, 27, 475784, tzinfo=utc)),
        ),
    ]
